### ISSUE TITLE
Unrecognised version number: 65

### ISSUE THREAD

**Issue by ramziShadid** [RNCryptor/JNCryptor#10]
i'm developing an application for android and iOS which communicate with PHP server, i am using RNCryptor to encrypt the data between them.

For both iOS , PHP encryption/decryption are working fine but in android the decryption are not working and giving me org.cryptonode.jncryptor.CryptorException: Unrecognised version number:65.

After tracing your code in Android you are supporting 2 versions of codes "2","3" and my encryption from the server "PHP" is returing 65

So do you have any idea what i'm doing wrong ?

**Comment by vados60** [comment]
have the same issue(

String to decode: "AwGBfFE6+BAQXP6iS/76r8eyzMlCUrIpGIiCJ1txpMw11hk32ObOniqi41T7BoG7dtXTecn4kOEh8NQQP MUxYzuwCb9kjaDyLcfDcWGh5JxTkA=="

key: "vRmfE690PF8u0123e24W7OdhF37g5e8g"

**Comment by FoneG** [comment]
> A (not so wild) guess here, but likely one side is using base64 to encode the output, the other isn't decoding it.

Your guess is correct that decoding money needs to do base64 processing first
