### ISSUE TITLE
Android and iOS compatibility issue

### ISSUE THREAD

**Issue by jakub17** [RNCryptor/JNCryptor#19]
The encryptor produces a byte array, that when encoded using Base64, produces a 112 character length string on iOS and 114 character length string on Android. Does this mean that JNCryptor and RNCryptor libraries aren't compatible after all? I noticed that the RNCryptor uses PKCS7Padding and JNCryptor uses PKCS5Padding. Is this the cause? How do I go about fixing this?

Thanks!

**Comment by rtoshiro** [comment]
I did not have tested your code, but usually, when I have this kind of problem, I look at Base64 in Android, because NO_WRAP is not the default option, and usually, you should use it.
Best.

**Comment by dmjones500** [comment]
Closing due to lack of response.
