### ISSUE TITLE
Android no method equivalent to iOS implementation

### ISSUE THREAD

**Issue by 4brunu** [RNCryptor/JNCryptor#24]
Hey, 

I used an encryption on the iOS side, but I can't create the equivalent in Android, because I can't find an equivalent public method to the following

``` objc
- (RNEncryptor *)initWithSettings:(RNCryptorSettings)settings
                         password:(NSString *)password
                               IV:(NSData *)anIV
                   encryptionSalt:(NSData *)anEncryptionSalt
                         HMACSalt:(NSData *)anHMACSalt
                          handler:(RNCryptorHandler)handler;
```

the only method that I found is this one and it's not public

``` java
byte[] encryptData(byte[] plaintext, char[] password, byte[] encryptionSalt,
      byte[] hmacSalt, byte[] iv) throws CryptorException {}
```

The problem is that I need to pass my own encryptionSalt, hmacSalt and iv, but I can't with this method, because it generate random data

``` java
public byte[] encryptData(byte[] plaintext, char[] password)
      throws CryptorException {

    byte[] encryptionSalt = getSecureRandomData(SALT_LENGTH);
    byte[] hmacSalt = getSecureRandomData(SALT_LENGTH);
    byte[] iv = getSecureRandomData(AES_BLOCK_SIZE);

    return encryptData(plaintext, password, encryptionSalt, hmacSalt, iv);
  }
```

Am I doing something wrong?

**Comment by mhamidg** [comment]
RNCryptor (for iOS) and JNCryptor (for Android) are not working together on file encryption/decryption throws a InvalidHMACException?
**RESOLUTION:**
on iOS side the password is lower case but in Android sometime password become upper case.
Use the password lower case `password.toCharArray()` to `password.toLowerCase().toCharArray() `

**Comment by rnapier** [comment]
@mhamidg I don't understand this question (and it doesn't seem related to this bug report). No RNCryptor implementation should be changing the case of the passed password. There is no Cryptor.kt in this package, however.

**Comment by mhamidg** [comment]
@rnapier my answer is about encryption and decryption using android and iOS. In Android Code, sometime password by default in upper case. So this is solution for that. I just edited the answer. that file 'Cryptor.kt' was in my project.

Thanks for correction.
