### ISSUE TITLE
Security issue on Android < 4.4

### ISSUE THREAD

**Issue by ysamlan** [RNCryptor/JNCryptor#25]
See http://android-developers.blogspot.com/2013/08/some-securerandom-thoughts.html

Since this library appears to be directly using numbers from a default-initialized `SecureRandom`, it should not be used on Android versions below 4.4 without a separate intialization step.

Either the fix should be applied in the code here where applicable (via reflection, probably, to avoid borking non-Android environments), or there should be a big disclaimer and a minimum Android recommendation of 4.4 rather than 2.3.3 for using this library.

**Comment by dmjones500** [comment]
Thank you for bringing this to my attention. I agree this affects JNCryptor and I'll immediately look into mitigation.

**Comment by msgrasser** [comment]
Has any work done on this? I'd love to use this library in [LDLN](https://github.com/ldln)'s Android client without a disclaimer on it that devices have to be 4.4+. Perhaps we could help look into nice ways of implementing this fix if it's not been started yet...

**Comment by rnapier** [comment]
Looking at the linked blog post, there is what seems to be a reasonable mitigation available by seeding the PRNG. Is there a problem with the code in that blog post?

**Comment by dmjones500** [comment]
I've decided not to address Android issues within this project. I don't have the means to test fixes, so this remains a pure Java implementation.
