### ISSUE TITLE
Decrypt remote file and save it on external storage

### ISSUE THREAD

**Issue by darkovski88** [RNCryptor/JNCryptor#27]
Hello, this is not really an issue with the library but I need some help with an android app that im working on. I'm getting a remote file, getting the input stream, decoding it and saving it to a file. The issue here is tha I cannot open the file - so I guess that the decoding is not right. Can someone of you guys help me?

Here is my code:
<code>
 new AsyncTask<Void, Void, Void>() {
            @Override
            protected Void doInBackground(Void... voids) {
                Log.d(TAG, "starting");

                JNCryptor cryptor = new AES256JNCryptor();

                try {
                    URL url = new URL(FILE_URL);
                    URLConnection conection = url.openConnection();
                    conection.connect();

                    // this will be useful so that you can show a tipical 0-100%
                    // progress bar

                    // download the file
                    InputStream input = new BufferedInputStream(url.openStream(),
                            8192);

                    //decrypt istream
                    byte[] b = null;
                    byte[] data = null;
                    try {
                        b = new byte[input.available()];
                        input.read(b);
                    } catch (IOException e) {
                        Log.i("decrypt error", e.toString());
                    }

                    AES256JNCryptorOutputStream cryptorStream = null;

                    ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
                    Log.d(TAG, "test b " + b.length + " | " + byteStream.size());
                    try {
                        cryptorStream = new AES256JNCryptorOutputStream(byteStream,
                                PASS.toCharArray());

                    } catch (CryptorException e) {
                        e.printStackTrace();
                    }

                    try {
                        cryptorStream.write(b);
                        cryptorStream.flush();
                        cryptorStream.close();
                    } catch (IOException e1) {
                        e1.printStackTrace();
                    }

                    byte[] encrypted = byteStream.toByteArray();

                    Log.d(TAG, "test encrypted=" + encrypted + " | " + byteStream.size()+" | "+encrypted.length);

                    try {
                        data = cryptor.decryptData(encrypted, PASS.toCharArray());
                        Log.d(TAG, "decrypted");
                    } catch (InvalidHMACException e) {
                        e.printStackTrace();
                        Log.d(TAG, "error");
                    } catch (CryptorException e) {
                        e.printStackTrace();
                        Log.d(TAG, "error 2");
                    }

                    if (data != null) {
                        Log.d(TAG, "data is ok");
                    }

                    //end decryption

                    // Output stream
                    //test
                    FileOutputStream fos = new FileOutputStream(Environment
                            .getExternalStorageDirectory().toString()
                            + "/temp.zip");
                    fos.write(data);
                    fos.close();
                    Log.d(TAG, "file saved ");

                    input.close();
                    Log.d(TAG, "done");
                } catch (Exception e) {
                    Log.d(TAG, "Error: " + e.getMessage());
                }
                return null;
            }
</code>

**Comment by dmjones500** [comment]
As stated in the question, this isn't a JNCryptor question. So I'm closing this issue.

There are several forums out there where you can probably find help with this question.
