### ISSUE TITLE
Out of memory when encrypted data is big

### ISSUE THREAD

**Issue by wangbourne** [RNCryptor/JNCryptor#28]
I have a file with a size of 100M, it will be out of memory when using encryptData. Is there any way to get through that?

**Comment by JavaMachine** [comment]
[This](http://stackoverflow.com/questions/1565388/increase-heap-size-in-java) should help

**Comment by dmjones500** [comment]
For large files, I suggest you use the streams to encrypt. That will potentially avoid holding the entire file in memory at once (although that depends how you use the stream, of course).
