### ISSUE TITLE
Reusing instance

### ISSUE THREAD

**Issue by JavaMachine** [RNCryptor/JNCryptor#32]
Me and my friend were developing application where we wanted to use this library. Several days ago my friend reported me that reusing instance will cause "HMACMismatch" ([Issue on iOS](https://github.com/RNCryptor/RNCryptor/issues/184) 

In my project I am keeping only one instance (using singletoon) and I haven't tested it yet...
My question is, should I create new instance for each decryption/encryption? Or I can leave one instance for whole application runtime?

Thanks in advance

**Comment by rnapier** [comment]
You need a new instance for each message that you encrypt or decrypt.
