### ISSUE TITLE
Is JNCryptor under active development, or being used by others integrating with RNCryptor?

### ISSUE THREAD

**Issue by LookingSharp** [RNCryptor/JNCryptor#35]
I haven't seen much in the way of changes to this repo in many years.  @dmjones500 or @rnapier do either of you know if this library is being actively used as an Android solution, or if there is a better v3 RNCryptor implementation for Android?

Thanks!

**Comment by TGIO** [comment]
[this](https://github.com/TGIO/RNCryptorNative) might be what you need

**Comment by rnapier** [comment]
@TGIO Very nice. Have you run this against the [test vectors](https://github.com/RNCryptor/RNCryptor-Spec/tree/master/vectors/v3)? If so, I'd be very interested in bringing this into the RNCryptor org if you're interested, or at least link to it from the main pages, as an official Android implementation (would this work for other Java platforms outside of Android? Would it be appropriate to merge directly into JNCryptor?)

My Java is quite weak, and I do no Android (or Java) development, so I have no direct involvement with this port, but I know that a performant Android implementation has been one of the biggest requests for years.

**Comment by TGIO** [comment]
@rnapier 
I have not run the test vectors or any android tests yet. But i'm going to. I'm using this library in production already. it is packed library taken from [RNCryptor-cpp](https://github.com/RNCryptor/RNCryptor-cpp). I'll be glad if you mark this as official Android implementation after i add couple missing features and tests to it. I'm not sure about other Java platforms but it works just great on android. Also i think that JNCryptor is good enough for other Java platforms (especially desktop) so i'm not sure about merging into it.

p.s i'll be glad if you help me out spreading word about my repo. More devs will know about it - more chance someone will contribute and fasten development up.

**Comment by LookingSharp** [comment]
Awesome!

**Comment by dmjones500** [comment]
@LookingSharp The code is dormant at the moment. I'm not really in a position to try and deliver an Android solution (not familiar with the platform, have a iPhone, etc.).

I'm thinking this will remain the pure Java solution, but I welcome and encourage someone to develop and maintain an Android fork.
