### ISSUE TITLE
Salt (or IV)

### ISSUE THREAD

**Issue by hatpick** [RNCryptor/JNCryptor#37]
I can see that both Salt (or IV) are being generated randomly, but let's say a user has two device A and B using the same app, would she be able to decrypt the data from device A on the device B without sharing Salt (or IV)?

**Comment by rnapier** [comment]
Yes. The salt and IV are transmitted as part of the message.

**Comment by hatpick** [comment]
I was wondering if it's secure that each time I have to pass the string password to encrypt/decrypt? That means that I have to hold on to the raw password somewhere in the memory or ask users' for their password each time.

**Comment by rnapier** [comment]
It is possible to avoid holding the password in memory, but it would depend on your exact use case. You would still need to hold the encryption keys in memory, but they don't stand out as much as passwords In any case it would be a fairly advanced usage and would likely require some amount of wrapping of the RNCryptor format. That's certainly possible (and I can certainly build that kind of thing on a consulting basis), but it's not currently supported in the open source code base.

The simplest approach (but see below) is to obfuscate the password in memory. This is most easily done by encrypting it against a long random password (a session password) generated when the user provides the master password. Encrypt the master password agains the session password, and store both. Then when you need the real password, decrypt it with the session password, use it, and then throw it away.

That said, it is not easy to overwrite memory in Java, particularly strings, so it may be quite challenging to get rid of the password once the the user has given it to you, making much of this moot unless you push all of the work into a JNI (and still tricky in that case). All of this only applies to situations where an attacker has significant access to the JVM. For more on the topic see http://security.stackexchange.com/a/75891/5304.
