### ISSUE TITLE
How to deal with AES256JNCryptorInputStream?

### ISSUE THREAD

**Issue by itinance** [RNCryptor/JNCryptor#41]
Are there any docs how to deal with AES256JNCryptorInputStream?
My task is to decrypt a whole file on the filesystem and i thought, this stream could maybe help here ...

Any hints are appreciated. Thanks!

**Comment by dmjones500** [comment]
What have you tried so far?

**Comment by babulpatel1309** [comment]
For too slow decryption and encryption here is the perfect solution.

[https://github.com/TGIO/RNCryptorNative?utm_source=android-arsenal.com&utm_medium=referral&utm_campaign=3643)](https://github.com/TGIO/RNCryptorNative?utm_source=android-arsenal.com&utm_medium=referral&utm_campaign=3643)

found this library while i was searching for alternatives of JNCryptor. This lib derived from native and it does pretty well job.
I had tried many solution but none of that was working and finally this library did. 

You can check the compare graph below.

![1](https://user-images.githubusercontent.com/7448808/29955838-3d08132a-8f00-11e7-9837-c5ccbbe0abbd.png)



![25](https://user-images.githubusercontent.com/7448808/29955837-3bbba702-8f00-11e7-94a7-e1307bf6eb15.png)

**Comment by dmjones500** [comment]
I'm closing this. Please re-open if you can better formulate your question.
