### ISSUE TITLE
decrypt issue on Android

### ISSUE THREAD

**Issue by petrorington** [RNCryptor/JNCryptor#42]
I have a problem with decrypt on Android. Basically I'm trying to decrypt the encrypted response which comes from web service (python) and it's encrypted with RNCryptor. When I'm trying to decrypt it, I always get the following error.
Unrecognised version number: -45.

The encrypted response from server is the following.
0301be65c81525dd2e9ea320f0e40dad2feba53d15cd1f9bfb8260a7a28f80501b184a536a24143a03c4edec2851d746f51098ca85f7b3de37c88bfe19814ef965baa3c50737749aef2c839466f573c6af43b1a232d94898396648827890b49c2c24f2fa1e7d43f8050207fada647924eccf

In iOS, decrypt is working fine.
Actually I'm using the following code to decrypt the response.

        private String decryptID(String encryptID) {
                String password = "X5vNjxL0Nh2rythdE1ra";
                JNCryptor cryptor = new AES256JNCryptor();

                try {
                    byte[] b;
                    b = Base64.decode(encryptID, 0);

                    byte[] plainText = cryptor.decryptData(b, password.toCharArray());
                    return new String(plainText);
                } catch (CryptorException e) {
                    // Something went wrong
                    e.printStackTrace();

                    return "0";
                }
            }

Please help to figure out the issue.

**Comment by babulpatel1309** [comment]
For too slow decryption and encryption here is the perfect solution.

[https://github.com/TGIO/RNCryptorNative?utm_source=android-arsenal.com&utm_medium=referral&utm_campaign=3643)](https://github.com/TGIO/RNCryptorNative?utm_source=android-arsenal.com&utm_medium=referral&utm_campaign=3643)

found this library while i was searching for alternatives of JNCryptor. This lib derived from native and it does pretty well job.
I had tried many solution but none of that was working and finally this library did. 

You can check the compare graph below.

![1](https://user-images.githubusercontent.com/7448808/29955838-3d08132a-8f00-11e7-9837-c5ccbbe0abbd.png)



![25](https://user-images.githubusercontent.com/7448808/29955837-3bbba702-8f00-11e7-94a7-e1307bf6eb15.png)

**Comment by dmjones500** [comment]
Your input data looks suspiciously like hexadecimal, rather than base64. Is that the root of the problem?

**Comment by dmjones500** [comment]
I'm going to close this issue. Please re-open if you still have problems.
