### ISSUE TITLE
how to compile that example?

### ISSUE THREAD

**Issue by TonyStark** [RNCryptor/JNCryptor#43]
I m completely new android development.
however i compiled/build full source using ```mvn install```
but i dont know how to compile/build this example>> https://github.com/RNCryptor/JNCryptor#using-jncryptor
can someone give me command or hint?
Thank you

**Comment by dmjones500** [comment]
Happy to discuss specific issues with the library, but for general questions about using Java libraries within Android, there is plenty of documentation available elsewhere online. Good luck.
