### ISSUE TITLE
 org.cryptonode.jncryptor.CryptorException: Unrecognised version number: 83

### ISSUE THREAD

**Issue by kampajch** [RNCryptor/JNCryptor#45]
I am using below code for descryption and it is giving me  " org.cryptonode.jncryptor.CryptorException: Unrecognised version number: 83" error.

/***
     * Method to Decrypt
     * @return
     * @throws CryptorException
     * @throws UnsupportedEncodingException
     */
    public String decryptData(String data) throws CryptorException, UnsupportedEncodingException {
        String password = "LSC@SD2017@ps";

        JNCryptor cryptor = new AES256JNCryptor();
        byte[] decode =   Base64.decode(data,Base64.NO_WRAP);

        byte[] decrypted = cryptor.decryptData(decode, password.toCharArray());

        String s = new String( decrypted ,"UTF-8");
        return s;
    }

This is the string to be decrypted:   Log.e("tag", decryptData( "U2FsdGVkX18x4uksV5otdPk2cc4Cj6UjNoYmSI7iKD00FMyK4KuGkpIw1uBgCkGF2dbE0ye1QjUaFo3BNv1Yr4CTqoSCB03lojmc++PJ+1VCZqXbqFzNMuAhCxWfKft/w+QgFbGf4sXKtDI/ky9AnxzDQTRdIuglPm+xS3CGj8MaWdBSghS4G98rFsDXOnKrfv4/ax0HkUZc7vrqUideUjd/nxBvNnG1qQd3EpFGOKuFVzmUrq89nSVrjcmKFJFLe5XVTf/MK8ofH8EPxepjKQgAycU8a839tB0Hl6djcVCFfNFqPLIp9pGwmF0iDEhWSQNI1y6bjV8AjO+Ggqp1Kw=="));

**Comment by rnapier** [comment]
That data is encrypted with OpenSSL, not RNCryptor. You'll need something that reads the OpenSSL data format.
