### ISSUE TITLE
Throws exception while decrypting 

### ISSUE THREAD

**Issue by SaravanakumarB** [RNCryptor/JNCryptor#47]
````java
    public static String encryptData(String data, String key) {
        byte[] decryptedData = data.getBytes();
        try {
            byte[] encryptedData = cryptor.encryptData(decryptedData, key.toCharArray());
            return new String(encryptedData);
        } catch (CryptorException e) {
            e.printStackTrace();
        }
        return null;
    }

    public static String decryptData(String data, String key) {
        try {
            byte[] encryptedData = data.getBytes();
            byte[] decryptedData = cryptor.decryptData(encryptedData, key.toCharArray());
            return new String(decryptedData);
        } catch (CryptorException e) {
            e.printStackTrace();
        }
        return null;
    }
````
I have used above encryption and decryption method.

**Comment by SaravanakumarB** [comment]
// i have used JNCryptor as global.
private static  JNCryptor cryptor = new AES256JNCryptor();

i got CryptorException when i run this code.

i have referred few issue posted previously about this.

**Comment by dmjones500** [comment]
This is wrong:
````java
return new String(encryptedData);
````
The encrypted data is binary and cannot be represented as a simple string. You are correct to think about using base64 instead.

Please show your full failing example with base64 and I can help further.

**Comment by SaravanakumarB** [comment]
org.cryptonode.jncryptor.InvalidHMACException: Incorrect HMAC value.org.cryptonode.jncryptor.AES256JNCryptor.decryptV3Data()
org.cryptonode.jncryptor.AES256JNCryptor.decryptV3Data()
org.cryptonode.jncryptor.AES256JNCryptor.decryptData()

**Comment by dmjones500** [comment]
Please read http://sscce.org. This explains how to create decent example code that allows others to help you.

**Comment by SaravanakumarB** [comment]
public class DVAESAlgorithm {
    private static  JNCryptor cryptor = new AES256JNCryptor();
    public static String encryptData(String data, String key) {
        byte[] decryptedData = data.getBytes();
        try {
            byte[] encryptedData = cryptor.encryptData(decryptedData, key.toCharArray());
            return new String(encryptedData);
        } catch (CryptorException e) {
            e.printStackTrace();
        }
        return null;
    }

    public static String decryptData(String data, String key) {
        try {
            byte[] encryptedData = Base64.decode(data,0);
            byte[] decryptedData = cryptor.decryptData(encryptedData, key.toCharArray());
            return new String(decryptedData);
        } catch (CryptorException e) {
            e.printStackTrace();
        }
        return null;
    }
}


// accessing these class from my adapter class, i just checked with my name to encrypt and decrypt

  String test = DVAESAlgorithm.encryptData("saravana kumar", encryptionKey);

  String value = DVAESAlgorithm.decryptData(test,encryptionKey);

// issue occured
org.cryptonode.jncryptor.CryptorException: Unrecognised version number: -81.
org.cryptonode.jncryptor.AES256JNCryptor.decryptData(AES256JNCryptor.java:283)

**Comment by SaravanakumarB** [comment]
you can check my code in below link.

https://github.com/SaravanakumarB/AES256-Algorithm
