### ISSUE TITLE
The encryption sends an exception

### ISSUE THREAD

**Issue by lucky-you** [RNCryptor/JNCryptor#51]
I was using encryption in Android Studio, but it was recognized as an exception and unrecognized version number was 123

**Comment by rnapier** [comment]
Do you mean you were decrypting something on Android that you encrypted elsewhere? Encryption should never throw an error about an unrecognized version; that’s a decryption error. 

Was the data encrypted by RNCryptor? A mismatched version generally means you’re trying to decrypt something that was encrypted in some other format.

**Comment by lucky-you** [comment]
I also use RNCryptor for encryption。I'm using Retrofit to request network data. Please help me figure it out. What can I do about it?

Encryption code：
@Override
    public RequestBody convert(T value) throws IOException {
        //加密操作，返回字节数组
        byte[] cipherText = new byte[0];
        JNCryptor encrypt = new AES256JNCryptor();
        byte[] plaintext = value.toString().getBytes();
        String password = ApiService.ENCRYPTION_PASSWORD;
        try {
            cipherText = encrypt.encryptData(plaintext, password.toCharArray());
        } catch (CryptorException e) {
            e.printStackTrace();
            Log.e("xy", "加密：" + e.getMessage());
        }
        Log.e("xy", "request中传递的json数据：" + value.toString());
        Log.e("xy", "加密后的字节数组：" + cipherText.toString());
        //传入字节数组，创建RequestBody 对象
        return RequestBody.create(MEDIA_TYPE, cipherText);
    }

Decryption code：
 @Override
    public T convert(ResponseBody responseBody) throws IOException {
        byte[] bytes = responseBody.bytes();
        //对字节数组进行解密操作
        char[] decryptPassword = ApiService.ENCRYPTION_PASSWORD.toCharArray();
        JNCryptor encrypt = new AES256JNCryptor();
        String decryptString = null;
        try {
            encrypt.decryptData(bytes, decryptPassword);
        } catch (CryptorException e) {
            e.printStackTrace();
            Log.e("xy", "解密：" + e.getMessage());
        }
        //对解密的字符串进行处理
        int position = decryptString.lastIndexOf("}");
        String jsonString = decryptString.substring(0, position + 1);
        Log.e("xy", "需要解密的服务器数据字节数组：" + bytes.toString());
        Log.e("xy", "解密后的服务器数据字符串：" + decryptString);
        Log.e("xy", "解密后的服务器数据字符串处理为json：" + jsonString);
        ResultResponse resultResponse = mGson.fromJson(jsonString, ResultResponse.class);
        return (T) resultResponse;
    }

**Comment by rnapier** [comment]
I don't know what `RequestBody.create()` is doing. Is it adding a wrapper? Is `responseBody` *exactly* the output of `encryptData` with nothing else and no encodings? The fact that the first byte is 123, which is `{` makes it very likely that you're reading JSON rather than the exact output of `encryptData`. (The version number is the first byte of the RNCryptor format, so whatever it complains about the version being is the first byte of its input.)

**Comment by dmjones** [comment]
Closing due to lack of response.
