### ISSUE TITLE
Empty Password

### ISSUE THREAD

**Issue by anhefti** [RNCryptor/JNCryptor#52]
Hi,

I'm currently in the situation that I have a file that was encrypted with an empty password (empty String) and I have to decrypt this with JNCryptor. This seems not to be possible since JNCryptor has a dedicated check on empty password to not allow this. 

Is there any way to pass or override this check and decrypt an input that was encrypted with empty password?

Thanks!

**Comment by dmjones** [comment]
>Is there any way to pass or override this check and decrypt an input that was encrypted with empty password?

No, I'm afraid this is not supported.
