### ISSUE TITLE
Unrecognised version number using Android 4.4 SDK

### ISSUE THREAD

**Issue by shaymargolis** [RNCryptor/JNCryptor#7]
I got an `CryptorException` by using this code:

```
JNCryptor cryptor = new AES256JNCryptor();
byte[] encryptedText = response_string.getBytes();
String password = "an16bytelongkey!an16bytelongkey!";

try {
    byte[] plaintext = cryptor.decryptData(encryptedText, password.toCharArray());
} catch (InvalidHMACException e1) {
    e1.printStackTrace();
    return;
} catch (org.cryptonode.jncryptor.CryptorException e1) {
    e1.printStackTrace();
    return;
}
```

`response_string` is a json string encrypted by RNCryptor in PHP.
the same code using Objective-C works.

(Full error: W/System.err﹕ org.cryptonode.jncryptor.CryptorException: Unrecognised version number: 65.)

**Comment by dharmakshetri** [comment]
@shaymargolis , it works perfectly.

**Comment by maplesnow-zsm** [comment]
@shaymargolis ,a new problem,it throw the exception:jncryptor.InvalidHMACException: Incorrect HMAC value. do you have any ideas?
